#Requires -Version 5.1
<#
.SYNOPSIS
  Build OpenBoson Windows onedir + optional Inno Setup installer.
#>
param(
    [string]$Version = "",
    [switch]$SkipInstaller,
    [string]$Channel = "stable",
    [string]$Repository = ""
)

$ErrorActionPreference = "Stop"
$Root = Resolve-Path (Join-Path $PSScriptRoot "..")
Set-Location $Root

if (-not $Version) {
    $pyproject = Get-Content (Join-Path $Root "pyproject.toml") -Raw
    if ($pyproject -match 'version\s*=\s*"([^"]+)"') {
        $Version = $Matches[1]
    } else {
        throw "Unable to determine version from pyproject.toml"
    }
}

Write-Host "Building OpenBoson $Version ($Channel)"

# Inject build info for packaged updater identity.
$repo = $Repository
if (-not $repo -and $env:GITHUB_REPOSITORY) { $repo = $env:GITHUB_REPOSITORY }
$buildInfo = @"
"""Generated by scripts/build_windows.ps1 — do not edit by hand."""

from __future__ import annotations

GITHUB_REPOSITORY: str | None = $(if ($repo) { "`"$repo`"" } else { "None" })
CHANNEL: str = "$Channel"
COMMIT: str | None = $(if ($env:GITHUB_SHA) { "`"$($env:GITHUB_SHA)`"" } else { "None" })
BUILD_TIME: str | None = "$(Get-Date -Format o)"
PACKAGED_VERSION: str | None = "$Version"


def update_checks_enabled() -> bool:
    return bool(GITHUB_REPOSITORY)
"@
$buildInfoPath = Join-Path $Root "src\openboson\_build_info.py"
$previousBuildInfo = Get-Content $buildInfoPath -Raw
Set-Content -Path $buildInfoPath -Value $buildInfo -Encoding utf8

try {
    python -m pip install -e ".[packaging]" | Out-Host
    python -m PyInstaller --noconfirm --clean openboson.spec | Out-Host

    $distApp = Join-Path $Root "dist\OpenBoson"
    if (-not (Test-Path (Join-Path $distApp "OpenBoson.exe"))) {
        throw "PyInstaller output missing OpenBoson.exe"
    }

    # Smoke: bundled content present (PyInstaller 6 onedir nests datas under _internal/)
    $banks = @(
        (Join-Path $distApp "data\demo_banks"),
        (Join-Path $distApp "_internal\data\demo_banks")
    ) | Where-Object { Test-Path $_ } | Select-Object -First 1
    $labs = @(
        (Join-Path $distApp "data\demo_labs"),
        (Join-Path $distApp "_internal\data\demo_labs")
    ) | Where-Object { Test-Path $_ } | Select-Object -First 1
    if (-not $banks) { throw "Bundled banks missing from dist (checked data/ and _internal/data/)" }
    if (-not $labs) { throw "Bundled labs missing from dist (checked data/ and _internal/data/)" }
    Write-Host "Bundled banks: $banks"
    Write-Host "Bundled labs:  $labs"

    if (-not $SkipInstaller) {
        $iscc = @(
            "${env:LocalAppData}\Programs\Inno Setup 6\ISCC.exe",
            "${env:ProgramFiles(x86)}\Inno Setup 6\ISCC.exe",
            "${env:ProgramFiles}\Inno Setup 6\ISCC.exe"
        ) | Where-Object { Test-Path $_ } | Select-Object -First 1

        if (-not $iscc) {
            Write-Warning "Inno Setup 6 (ISCC.exe) not found; skipping installer. Dist onedir is ready."
        } else {
            New-Item -ItemType Directory -Force -Path (Join-Path $Root "dist\installer") | Out-Null
            & $iscc "/DMyAppVersion=$Version" (Join-Path $Root "installer\OpenBoson.iss")
            $setup = Join-Path $Root "dist\installer\OpenBoson-Setup-$Version.exe"
            if (-not (Test-Path $setup)) { throw "Installer not produced: $setup" }

            $hash = (Get-FileHash -Algorithm SHA256 $setup).Hash.ToLowerInvariant()
            $name = Split-Path $setup -Leaf
            Set-Content -Path "$setup.sha256" -Value "$hash  $name" -Encoding ascii

            $bytes = (Get-Item $setup).Length
            $manifest = @{
                version                 = $Version
                channel                 = $Channel
                tag                     = "v$Version"
                asset_name              = $name
                bytes                   = $bytes
                sha256                  = $hash
                minimum_updater_version = "0.2.0"
                release_url             = "https://github.com/$($repo -replace '^$','openboson/openboson')/releases/tag/v$Version"
            } | ConvertTo-Json -Depth 4
            Set-Content -Path (Join-Path $Root "dist\installer\OpenBoson-$Version.json") -Value $manifest -Encoding utf8
            Write-Host "Installer + checksum + manifest written under dist/installer"
        }
    }
}
finally {
    Set-Content -Path $buildInfoPath -Value $previousBuildInfo -Encoding utf8
}

Write-Host "Done."
