"""Per-question authored explanations (question_id → teaching text).

Do not add a global map keyed only by choice text. A fact about VLANs, NAT,
or netmiko belongs here only when that question’s stem is actually about it.
"""

from __future__ import annotations

HAND_EXPL: dict[str, str] = {
    "ccna-3-009": (
        "Cisco IOS does **longest prefix match** first. `10.1.1.5` matches both "
        "`10.1.1.0/28` (28 bits) and `10.1.0.0/16` (16 bits); the /28 is installed "
        "even if the /16 has a better administrative distance or metric.\n\n"
        "**10.1.1.0/28 over 10.1.0.0/16** wins because 28 matching bits beat 16.\n\n"
        "**Always AD only** is consulted only among routes to the **same prefix** "
        "from different sources (for example OSPF AD 110 vs EIGRP AD 90). AD does "
        "not override a longer match.\n\n"
        "**Always metric only** (OSPF cost, EIGRP composite) ranks paths **inside "
        "one protocol** after the prefix length is already chosen. A /16 with cost "
        "1 still loses to a /28 with cost 100.\n\n"
        "**Random ECMP only** appears when prefix length, AD, and metric are all "
        "equal (`maximum-paths`). It never beats a longer prefix."
    ),
    "ccna-3-010": (
        "Cisco `show ip route` codes: **C** connected, **L** local, **S** static, "
        "**S*** candidate default static (gateway of last resort), **O** OSPF, "
        "**B** BGP, **D** EIGRP, **R** RIP.\n\n"
        "**Candidate default static** is **S*** — typically `ip route 0.0.0.0 "
        "0.0.0.0 nh` marked as the gateway of last resort.\n\n"
        "**OSPF summary** shows as **O IA** (inter-area Type-3) or **O** for an "
        "intra-area prefix, never S*.\n\n"
        "**BGP aggregate** lives in the BGP table (`aggregate-address`) and "
        "installs as **B** or **B***>, not S*.\n\n"
        "**Connected** is code **C** — a prefix on an up/up interface. It is a "
        "directly attached network, not a static default."
    ),
    "encor-3-002": (
        "OSPFv3 (RFC 5340) was designed to route **IPv6**. On IOS-XE it also "
        "supports address-families (`router ospfv3` / `address-family ipv6` or "
        "`ipv4`), but it is the IPv6-era OSPF, not a classful IPv4, IPX, or "
        "AppleTalk protocol.\n\n"
        "**IPv6 (address-family designs)** is what OSPFv3 carries (IPv6 LSAs, "
        "optional IPv4 AF on modern images).\n\n"
        "**Only IPv4 classful** is RIPv1/IGRP behavior (Class A/B/C masks). OSPF "
        "has been classless since OSPFv2; OSPFv3 is not classful IPv4.\n\n"
        "**Only IPX** is Novell NetWare’s IPX/SPX stack. Cisco removed IPX "
        "routing; OSPFv3 does not encapsulate or advertise IPX.\n\n"
        "**Only AppleTalk** is Apple’s legacy Phase-2 network (RTMP / EIGRP for "
        "AppleTalk). It was never carried in OSPFv3 LSAs."
    ),
    "ccna-3-014": (
        "VRRP (RFC 5798) is the **IETF standards-based** first-hop redundancy "
        "protocol: hosts use a virtual IP, and one router is master (default "
        "priority 100) owning the virtual MAC `0000.5e00.01xx`.\n\n"
        "**Standards-based FHRP** is VRRP — vendors including Cisco implement "
        "the open spec (`vrrp N ip A.B.C.D`).\n\n"
        "**Cisco-only proprietary** is **HSRP** (or GLBP). Those are Cisco "
        "protocols; VRRP is the multi-vendor standard, so a Juniper or Arista "
        "peer can share the same VIP.\n\n"
        "**A link-state IGP** is OSPF or IS-IS exchanging LSAs and running SPF. "
        "VRRP does not advertise prefixes or compute a topology; it only elects "
        "who owns the default-gateway IP/MAC on a LAN.\n\n"
        "**A wireless roaming protocol** (802.11r/k/v or CAPWAP mobility) moves "
        "clients between APs. VRRP is a wired first-hop gateway election, not "
        "RF roaming."
    ),
    "ccna-3-017": (
        "`show ip route` displays the IPv4 routing table (RIB): route codes, "
        "prefixes, AD/metric, next hops, and the gateway of last resort.\n\n"
        "**show ip route** is the command that prints that IPv4 RIB.\n\n"
        "**show vlan brief** lists VLAN IDs, names, and access ports on a "
        "switch. It has no IPv4 prefixes or next hops.\n\n"
        "**show cdp neighbors** lists Cisco Layer-2 neighbors (device ID, local "
        "and remote interfaces). It is topology discovery, not the routing "
        "table.\n\n"
        "**show spanning-tree** shows STP root, port roles, and states per VLAN. "
        "It does not list IP routes."
    ),
    "encor-3-015": (
        "MSDP (Multicast Source Discovery Protocol) peers **Rendezvous Points in "
        "different PIM-SM domains** and exchanges Source-Active messages (typically "
        "TCP 639) so each RP learns remote (S,G) sources — often with anycast RP.\n\n"
        "**PIM domains’ RPs** are exactly what MSDP interconnects.\n\n"
        "**Only VLANs** are 802.1Q Layer-2 broadcast domains. MSDP does not "
        "create, trunk, or prune VLANs; it is an RP-to-RP multicast protocol.\n\n"
        "**Only AAA servers** (RADIUS/TACACS+) authenticate operators or 802.1X "
        "users. MSDP SA messages are not login traffic.\n\n"
        "**Only syslog** exports device logs (UDP 514). An MSDP SA is a multicast "
        "source advertisement, not a log message."
    ),
    "encor-3-019": (
        "On an edge router, NAT/PAT (`ip nat inside source list ... overload`) "
        "translates inside-local addresses so private hosts can reach outside/"
        "public networks.\n\n"
        "**Translate inside addresses for outside reachability** is that NAT/PAT "
        "job (and PAT multiplexes via source ports).\n\n"
        "**Only hash EtherChannels** (`port-channel load-balance src-dst-ip`) "
        "picks a member link inside a bundle. Hashing does not translate IPs.\n\n"
        "**Only elect DR** is OSPF on a multiaccess link (`ip ospf priority`). "
        "NAT does not run a DR/BDR election.\n\n"
        "**Only set STP priority** (`spanning-tree vlan N priority`) elects a "
        "Layer-2 root bridge. That is switching, not address translation."
    ),
    "ccna-1-010": (
        "VLSM allocates the **largest** blocks first so leftover space stays "
        "contiguous. Order: list each subnet’s host requirement, sort those "
        "counts descending, assign the biggest prefixes first, then document "
        "what address space remains.\n\n"
        "Listing hosts first tells you the required prefix lengths. Sorting "
        "descending is what makes “largest first” well-defined. Documenting "
        "leftover space last is how the next VLAN or site gets a free block."
    ),
    "ccna-2-006": (
        "Classic 802.1D port states in order: **Blocking** (no user frames, BPDUs "
        "listened) → **Listening** (BPDUs, still no learning/forwarding) → "
        "**Learning** (source MACs learned, still no forwarding) → **Forwarding** "
        "(user frames). RSTP collapses blocking/listening into discarding, but "
        "this item is the 802.1D teaching sequence."
    ),
    "ccna-3-001": (
        "OSPF neighbors move **Down → Init → 2-Way → ExStart → Exchange → "
        "Loading → Full**. Down is no Hellos. Init is a Hello heard. 2-Way is "
        "bidirectional (DR election can finish here on a LAN). ExStart/Exchange/"
        "Loading master the DD and flood LSAs. Full means the LSDBs match."
    ),
    "encor-3-090": (
        "Cisco BGP best-path among the listed attributes: highest **Weight** "
        "(local to the router) → highest **Local Preference** (inside the AS) → "
        "lowest **MED** (compared for the same neighboring AS) → prefer **eBGP** "
        "over iBGP. Weight is Cisco-proprietary and is considered first of these."
    ),
    "ccna-1-011": (
        "Private cloud keeps compute, storage, and network for **one organization** "
        "(on-prem or a dedicated hosted tenancy). That is the exclusive-use model.\n\n"
        "**Private cloud** is single-tenant: the org controls who shares the "
        "infrastructure.\n\n"
        "**Public cloud** (AWS/Azure/GCP) is multi-tenant. Many customers share the "
        "provider’s fabric, so it is not exclusive to one org.\n\n"
        "**Community only** is shared by several organizations with a common mission "
        "(for example a set of agencies). More than one tenant.\n\n"
        "**Hybrid CDN** mixes on-prem with a content-delivery overlay. A CDN caches "
        "content; it is not a single-tenant private cloud."
    ),
    "ccna-1-023": (
        "RFC 1918 private IPv4: **10.0.0.0/8** (Class A), **172.16.0.0/12** "
        "(Class B), **192.168.0.0/16** (Class C).\n\n"
        "**10.0.0.0/8** is the Class A private block (10.0.0.0–10.255.255.255).\n\n"
        "**172.32.0.0/12** is not RFC 1918. The private Class B block is "
        "**172.16.0.0/12** (172.16.0.0–172.31.255.255). 172.32.0.0 is public.\n\n"
        "**192.169.0.0/16** is public. The Class C private block is "
        "**192.168.0.0/16**.\n\n"
        "**198.51.100.0/24** is TEST-NET-2 (RFC 5737 documentation), not a private "
        "range."
    ),
    "ccna-1-027": (
        "On Windows, **`ipconfig`** (and `ipconfig /all`) prints IPv4/IPv6, mask, "
        "and default gateway per adapter.\n\n"
        "**ipconfig** is the Windows client command for that output.\n\n"
        "**ifconfig only (Windows default)** is a Unix/Linux command. Current "
        "Windows does not ship `ifconfig` as the default IP display tool.\n\n"
        "**show ip route** is Cisco IOS — it dumps the router RIB, not a Windows "
        "NIC.\n\n"
        "**route print only without IP** shows the Windows routing table. It does "
        "not list the adapter address and mask the way `ipconfig` does."
    ),
    "ccna-1-029": (
        "**Single-mode fiber (SMF)** has a ~9 µm core and carries one mode for long "
        "reach (km). **Multimode (MMF)** has a 50/62.5 µm core for shorter "
        "building/campus runs.\n\n"
        "**Core size / distance capability** is the primary physical difference.\n\n"
        "**Only connector color mandatory** (blue UPC vs green APC, beige vs aqua) "
        "is a convention, not what makes SMF go farther.\n\n"
        "**Only PoE support** is a copper Ethernet feature (802.3af/at/bt). Fiber "
        "does not carry PoE.\n\n"
        "**Only VLAN tagging** is 802.1Q on frames. Both SMF and MMF carry tagged "
        "Ethernet; tagging is not an optical-mode property."
    ),
    "ccna-2-017": (
        "A **VTP transparent** switch does not originate or apply VTP updates to "
        "its own VLAN database. It **forwards** advertisements on trunks so a "
        "server/client domain can still pass through (`vtp mode transparent`).\n\n"
        "**Forward them but do not sync VLAN DB from them** is transparent-mode "
        "behavior. VLANs are created locally on that switch.\n\n"
        "**Always overwrite clients** is **VTP server** behavior when a higher "
        "revision arrives. Transparent switches do not overwrite anyone’s VLAN DB "
        "from VTP.\n\n"
        "**Drop all BPDUs** is STP (BPDU Guard/Filter). VTP messages are not STP "
        "BPDUs.\n\n"
        "**Disable all trunks** would isolate VLANs from neighbors. Transparent "
        "mode still trunks; it just ignores VTP for its own database."
    ),
    "ccna-2-019": (
        "EtherChannel members must match **speed, duplex, switchport mode, native "
        "VLAN, allowed VLAN set, and LACP/PAgP mode**. A mismatch suspends the "
        "member (`show etherchannel summary` shows `(s)`).\n\n"
        "**Speed/duplex and compatible configs** is that consistency rule.\n\n"
        "**Unique VLANs only** is the opposite: members should carry the **same** "
        "allowed VLANs, not unique ones.\n\n"
        "**Different native VLANs** on members leak untagged traffic and typically "
        "prevent a clean bundle. Natives must match.\n\n"
        "**Random MTUs** (`system mtu` / per-interface MTU) must match; random MTUs "
        "drop or suspend members."
    ),
    "ccna-2-021": (
        "If two trunk ends use different **native VLANs**, untagged frames land in "
        "different VLANs — a VLAN leak. Cisco CDP reports `Native VLAN mismatch` "
        "and connectivity for the untagged VLAN breaks.\n\n"
        "**CDP warnings and possible connectivity issues** is the typical symptom.\n\n"
        "**Automatic OSPF adjacency** is a Layer 3 event (`show ip ospf neighbor`). "
        "A native-VLAN leak does not form OSPF.\n\n"
        "**Mandatory encryption** is not triggered by a native mismatch. 802.1Q has "
        "no encryption requirement.\n\n"
        "**DHCP snooping disable** is a separate L2 security feature. A native "
        "mismatch does not turn snooping off."
    ),
    "ccna-3-012": (
        "OSPF **areas** hierarchicalize the domain so Type-1/2 LSAs stay inside an "
        "area. ABRs originate Type-3 summaries instead of flooding every intra-area "
        "LSA everywhere. That **limits LSA flooding** and shrinks LSDBs/SPF.\n\n"
        "**Limit LSA flooding scope** is why areas exist.\n\n"
        "**Replace IP addresses** is NAT (or an addressing redesign). Areas do not "
        "translate prefixes.\n\n"
        "**Encrypt all payloads** is IPsec/TLS. OSPF can authenticate Hellos "
        "(`ip ospf authentication`), but an area is not an encryption boundary.\n\n"
        "**Terminate VLANs** is an SVI / ROAS / L3-switch job. Area 0 vs area 1 is "
        "an OSPF LSDB boundary, not a VLAN terminator."
    ),
    "ccna-3-018": (
        "An **ABR** has at least one link in **area 0** and one link in a "
        "**non-backbone area**. It originates Type-3 summary LSAs between those "
        "areas (`show ip ospf border-routers`).\n\n"
        "**Area 0 and non-backbone areas (typically)** is that ABR placement.\n\n"
        "**Only two autonomous systems** describes an **ASBR** (or eBGP) connecting "
        "OSPF to another routing domain, not two OSPF areas.\n\n"
        "**Only VLANs** are L2 broadcast domains. An ABR is an OSPF router role, "
        "not a VLAN.\n\n"
        "**Only wireless controllers** terminate CAPWAP. They are not OSPF area "
        "borders."
    ),
    "ccna-1-017": (
        "**DNS** maps names to addresses: **A** (IPv4) and **AAAA** (IPv6) for "
        "forward lookup, **PTR** for reverse.\n\n"
        "**Names to IP addresses** is that primary job (plus reverse).\n\n"
        "**MAC to VLAN** is a switch CAM / access-VLAN assignment "
        "(`switchport access vlan`), not DNS.\n\n"
        "**AS numbers to communities** is BGP policy (`set community`), not name "
        "resolution.\n\n"
        "**SPIDs to DLCI** are ISDN and Frame Relay identifiers — legacy WAN, not "
        "DNS."
    ),
    "ccna-4-012": (
        "A **forward lookup** asks “what address has this name?” and returns "
        "**A/AAAA**. Reverse (PTR) is the other direction.\n\n"
        "**Name to IP** is forward DNS.\n\n"
        "**IP to MAC only** is **ARP** (or NDP for IPv6) on the local LAN, not DNS.\n\n"
        "**AS to community** is a BGP attribute mapping, not DNS.\n\n"
        "**VLAN to VNI** is a VXLAN/EVPN encapsulation mapping, not DNS."
    ),
    "ccna-4-014": (
        "**Policing** meters a class and **drops** or **remarks** (for example to "
        "DSCP AF) packets over a committed rate (`police cir ... exceed-action "
        "drop`). It does not buffer/delay like shaping.\n\n"
        "**Drops or remarks excess over a rate** is the policer action.\n\n"
        "**Only increases STP diameter** would add switches/hops to spanning tree. "
        "A QoS police map does not change STP diameter.\n\n"
        "**Only creates VLANs** is `vlan N`. Policers live in a policy-map, not "
        "the VLAN database.\n\n"
        "**Only disables CDP** is `no cdp enable`. Unrelated to rate enforcement."
    ),
    "ccna-4-019": (
        "**`show ntp associations`** lists NTP peers, stratum, reach, delay, and "
        "which server is selected (`*`).\n\n"
        "**show ntp associations** is the IOS command for that table.\n\n"
        "**show vlan brief** lists L2 VLANs on a switch — no NTP.\n\n"
        "**show spanning-tree** shows STP root/roles/states — no NTP.\n\n"
        "**show etherchannel summary** shows Port-Channel members — no NTP."
    ),
    "ccna-5-010": (
        "Named ACLs are built in **`ip access-list standard NAME`** or "
        "**`ip access-list extended NAME`** mode, then `permit`/`deny` lines, then "
        "`ip access-group NAME in/out` on an interface.\n\n"
        "**ip access-list standard/extended NAME** is that configuration mode.\n\n"
        "**Only interface vlan exclusively** is SVI config (`interface vlan 10`). "
        "You may *apply* an ACL there, but you do not *create* a named ACL under "
        "the SVI.\n\n"
        "**Only line vty without ACL** is `line vty 0 4`. VTY uses `access-class`, "
        "and you still define the ACL with `ip access-list` first.\n\n"
        "**Only spanning-tree mode** is `spanning-tree mode rapid-pvst`. It has "
        "nothing to do with ACL syntax."
    ),
    "ccna-5-013": (
        "A **vulnerability** is a weakness. An **exploit** is a method or tool that "
        "**takes advantage** of that weakness to violate CIA. A **threat** is the "
        "actor who might use it.\n\n"
        "**A method that takes advantage of a vulnerability** is the definition of "
        "an exploit.\n\n"
        "**Only a firewall** is a control that can *block* exploits; it is not "
        "itself an exploit.\n\n"
        "**Only a syslog facility** is a log channel (`local0`…`local7`). Logging "
        "may *record* an exploit; it is not one.\n\n"
        "**Only a VLAN** is an L2 broadcast domain. Segmentation can reduce blast "
        "radius; a VLAN is not an exploit."
    ),
    "encor-1-007": (
        "In a VXLAN/EVPN or SD-Access fabric, the **anycast gateway** is the "
        "**same SVI IP (and often MAC)** configured on every leaf. Hosts ARP to a "
        "local leaf instead of hairpinning to a distant HSRP pair.\n\n"
        "**Same gateway IP on multiple leaves** is that anycast SVI.\n\n"
        "**Unique gateway per VLAN only globally** would force all traffic to one "
        "central first-hop, which is the opposite of anycast.\n\n"
        "**Only HSRP v1 required** is a campus FHRP (virtual IP/MAC, active/"
        "standby). Fabric anycast does not require HSRPv1.\n\n"
        "**Only GLBP** is Cisco’s load-sharing FHRP with AVG/AVF. Fabric anycast "
        "is not GLBP."
    ),
    "encor-1-016": (
        "When a traditional campus must talk to **SD-Access**, traffic crosses a "
        "**border/fusion** node: fabric VN to VRF-lite, SGT mapping, and often a "
        "fusion router for shared services (DHCP/DNS/Internet).\n\n"
        "**Border/fusion design considerations** is that interop.\n\n"
        "**Only disabling all routing** would isolate the sites. You still need "
        "underlay and fusion routing.\n\n"
        "**Only removing VLANs forever** is unnecessary; the traditional side still "
        "uses VLANs, mapped into fabric VNs at the border.\n\n"
        "**Only Token Ring bridges** are obsolete L2. SD-Access interop is "
        "IP/VXLAN/LISP, not Token Ring."
    ),
    "encor-2-010": (
        "**GRE** tunnels any payload (including multicast/IGP) but is cleartext. "
        "**IPsec** (tunnel, VTI, or IPsec protecting GRE) **encrypts** that overlay "
        "so site-to-site traffic is confidential.\n\n"
        "**Encrypt tunneled overlays** is why GRE+IPsec (or an IPsec VTI) is used.\n\n"
        "**Only hash EtherChannels** is `port-channel load-balance src-dst-ip`. "
        "That is CEF hashing on a bundle, not IPsec.\n\n"
        "**Only elect DR** is OSPF on a multiaccess link. IPsec/GRE does not elect "
        "a DR.\n\n"
        "**Only age CAM** is MAC-table aging on a switch. Unrelated to overlay "
        "encryption."
    ),
    "encor-3-017": (
        "OSPFv3 Hello includes an **Instance ID**. Routers on the same link form "
        "an adjacency only if Instance IDs match. That lets **multiple OSPFv3 "
        "instances** share a physical or VLAN interface (for example one instance "
        "per VRF or address-family) without merging LSDBs.\n\n"
        "**Multiple instances on a link** is what Instance ID distinguishes.\n\n"
        "**Only VLAN IDs** are 802.1Q tags. You can run OSPFv3 on an SVI, but the "
        "Instance ID is **not** the VLAN ID — two instances can share one VLAN.\n\n"
        "**Only DSCP** marks IP for QoS. DSCP does not select an OSPFv3 instance.\n\n"
        "**Only ASN** is BGP. OSPFv3 uses a process/instance ID here, not an AS "
        "number."
    ),
    "encor-3-028": (
        "Multicast **RPF** (Reverse Path Forwarding) accepts a (S,G) packet only "
        "on the interface the unicast RIB would use **toward S**. A packet arriving "
        "on the wrong interface is dropped. That stops loops and some spoofed "
        "sources.\n\n"
        "**Accepting multicast on the wrong reverse path** is what RPF prevents.\n\n"
        "**Only TCP SYN floods exclusive** are a unicast DoS (CoPP, SYN cookies). "
        "RPF is a multicast forwarding check, not a SYN-flood mitigator.\n\n"
        "**Only VLAN hopping exclusive** is an L2 attack (double-tag / native "
        "VLAN). RPF does not inspect 802.1Q.\n\n"
        "**Only DNS amplification exclusive** is a reflection DDoS on UDP 53. "
        "Multicast RPF is specifically the (S,G) reverse-path check."
    ),
    "encor-3-032": (
        "Cisco **weight** is a 16-bit attribute **local to this router** (default "
        "32768 for originated, 0 for learned). Highest weight wins **first** in "
        "the BGP best-path list. It is never advertised in UPDATE messages.\n\n"
        "**Local to the router and highest preferred first** is weight.\n\n"
        "**Transitive across the AS always** describes attributes like **AS_PATH** "
        "or optional-transitive communities. Weight is non-transitive — neighbors "
        "never see it.\n\n"
        "**Only an OSPF metric** is cost (reference-bw/bandwidth) inside OSPF. BGP "
        "weight is not OSPF cost.\n\n"
        "**Only a VLAN ID** is 1–4094 on a trunk. Unrelated to BGP best-path."
    ),
    "encor-4-009": (
        "**IP SLA jitter** (`udp-jitter`) measures delay, jitter, and loss toward "
        "a responder — the numbers used to judge **voice/video** path quality "
        "(and to feed tracking/PfR).\n\n"
        "**Voice/video path quality assessment** is the use case.\n\n"
        "**Only VLAN creation** is `vlan N`. SLA probes do not create VLANs.\n\n"
        "**Only ACL lines** are `permit`/`deny` entries. SLA is `ip sla N` / "
        "`udp-jitter`.\n\n"
        "**Only VTP password** authenticates VTP. Unrelated to jitter probes."
    ),
    "encor-6-013": (
        "**Cisco SD-WAN Manager** (vManage) exposes REST APIs to **push templates, "
        "policies, and operational queries** against the WAN fabric — inventory, "
        "device config, App-route/AAR policy — rather than clicking every "
        "vEdge/cEdge.\n\n"
        "**Automate WAN fabric operations/policy** is that API role.\n\n"
        "**Only set STP priority** is `spanning-tree vlan N priority` on a campus "
        "switch. vManage APIs are not an STP tool.\n\n"
        "**Only create VLANs on access** is access-layer switching. SD-WAN Manager "
        "drives WAN overlay and policy.\n\n"
        "**Only configure PortFast** is `spanning-tree portfast`. Not an SD-WAN "
        "Manager function."
    ),
    "encor-6-016": (
        'A Python **dict** maps **keys to values** (`d["rid"] = "1.1.1.1"`). '
        "That is the core associative array used in NETCONF/REST payloads and "
        "scripts.\n\n"
        "**Keys to values** is the definition.\n\n"
        "**Only VLANs to VNIs exclusive** might be *one* dict you write "
        "(`{10: 10010}`), but dicts are a general type, not a VLAN/VNI structure.\n\n"
        "**Only AS paths** are BGP attributes (lists of ASNs), not Python’s dict "
        "type.\n\n"
        "**Only STP costs exclusive** are integers on switch ports "
        "(`spanning-tree cost`). Not what a dict is."
    ),
}
